### ISSUE TITLE
Where should secondary NoahMP modules (e.g., glacier) live?

### ISSUE THREAD

**Issue by aubreyd** [NCAR/noahmp#1]
Just cross-referencing Issue 499 from WRF-Hydro repo... https://github.com/NCAR/wrf_hydro_nwm_public/issues/499

**Comment by cenlinhe** [comment]
In principle, it should be possible to include NoahMP_glacier to the main module_sf_noahmplsm.F. However, it seems that not many users apply Noah-MP to glacier points. Also, eventually as we refactor the entire Noah-MP, the problem should be solved, where things will be modularized.

**Comment by ncarchen** [comment]
For, have we decided to maintain that module in the new HRLDAS repo?

**Comment by cenlinhe** [comment]
For now, I think we will still keep the glacier one as it is (outside noahmplsm.F) in the HRLDAS repo. Let's see if we will have the possibility to incorporate it in the noahmplsm.F when doing the refactoring.
