### ISSUE TITLE
negative theta_1500 in PedoTransferSR2006Mod.F90

### ISSUE THREAD

**Issue by tslin2** [NCAR/noahmp#110]
The pedotransfer function calculates the negative theta_1500, so the model has floating invalid issue using log function at calculating the BEXP
https://github.com/NCAR/noahmp/blob/1a853a5df5fc706af4b96cf27d4d41affaad57df/drivers/hrldas/PedoTransferSR2006Mod.F90#L173

See below example,
sand: 0.7781111      
clay: 7.7999993E-03
theta_1500: -1.1482276E-03

adding the following two constraints 
    
    theta_33    = max(10.0**-5.0,theta_33)  ! For numerical stability
    theta_1500  = max(10.0**-5.0,theta_1500)  ! For numerical stability

before 
https://github.com/NCAR/noahmp/blob/1a853a5df5fc706af4b96cf27d4d41affaad57df/drivers/hrldas/PedoTransferSR2006Mod.F90#L165
can revolve

**Comment by cenlinhe** [comment]
Thank you for pointing out this. This PedoTransfer function was not tested by any application before, so this bug was not detected. I will fix this soon.
