### ISSUE TITLE
SNEQV depleting but not being accounted for in simulations

### ISSUE THREAD

**Issue by GAaronAlexander** [NCAR/noahmp#47]
I have been running Noah-MP in offline mode using ERA5 as a forcing for some model development, and I came across and issue that I wanted to bring to your attention. In the snow module `COMBINE`, there is an if else statement that uses the following call:
`IF (ISNOW_OLD < -1) THEN` (around ~7000 in module_sf_noamplsm.F)

This was causing an issue, when snow jumped more then one level (in my case going from a 2 snow layers to no snow layers) the loop would not account for the loss of snow water equivalent, and then trigger the ERROR module for water balances. 

I seem to have fixed this by taking the advice of the comment from MB/KM and change the if else statement to be 
`IF (ISNOW < -1) THEN`

1) Is this a physically feasible correction to implement? and if so 2) I wanted to bring this to your attention!

**Comment by cenlinhe** [comment]
Hi, thank you for bringing up this issue. Could you please be more specific about which part you were referring to within COMBINE subroutine? I am not sure which line(s) exactly is. Maybe you could provide more lines within this if-statement to help us spot the exact place. Thanks!

**Comment by cenlinhe** [comment]
@barlage Mike, do you know what exactly this issue is? The user did not reply to me.

**Comment by GAaronAlexander** [comment]
Hi @cenlinhe! I am so sorry for the delay in responding! I don't know how this fell off the plate! 

The error is on line 6657. Originally, it was checking the ISNOW_OLD variable.  There is a comment that says ("change to ISNOW"), off to the side, which is what I did and it seems to work now like a dream! 

Let me know if you need more information!

**Comment by cenlinhe** [comment]
@GAaronAlexander Thank you for the clarification!

**Comment by cenlinhe** [comment]
@barlage I feel like we should use change it to "IF (ISNOW < **0**) THEN" instead of "IF (ISNOW < **-1**) THEN". Mike, what do you think?

**Comment by cenlinhe** [comment]
This bug has been fixed in this commit: https://github.com/NCAR/noahmp/commit/218eb5a7b41c62c700eeba798a71004720b55264
So I am going to close this issue.
