### ISSUE TITLE
Bug in mixing ratio calculation within Jarvis scheme

### ISSUE THREAD

**Issue by cenlinhe** [NCAR/noahmp#56]
https://github.com/NCAR/noahmp/blob/43bcf9d2f58cb43ccea2ab8d43b8fd3018c006b2/src/module_sf_noahmplsm.F#L5192

Should the above "Q2 = Q2 / (1.0 + Q2)" be "Q2 = Q2 / (1.0 - Q2)" for the conversion from specific humidity to mixing ratio?
@CharlesZheZhang Could you please double check?

**Comment by CharlesZheZhang** [comment]
Hi Cenlin, I confirmed with you that this should be Q2/(1.0 -Q2) to convert specific humidity to mixing ratio.

**Comment by cenlinhe** [comment]
OK, thanks! I will fix this bug.
