### ISSUE TITLE
Xiananjiang or Xinanjiang ?

### ISSUE THREAD

**Issue by andrewsoong** [NCAR/noahmp#59]
There is a very small mistake in line 117 from src/module_sf_noahmplsm.F.
!   7 -> Xiananjiang Infiltration and surface runoff scheme ((Jayawardena and Zhou, 2000)
Perhaps Xinanjiang is right.

Also， in WRF and WRF User guide，This small mistake may also need to be corrected.
Thanks！

**Comment by cenlinhe** [comment]
Thank you for pointing this out. We will fix this typo as soon as possible along with WRF.

**Comment by cenlinhe** [comment]
We have corrected this typo in the latest noah-mp version, so I am closing this issue now.
